//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertificateId { get; set; }
        public string CertificateDate { get; set; }
        public string CertificateExpires { get; set; }
        public string Notes { get; set; }
        public string CompanyName { get; set; }
        public string Name { get; set; }
        public Nullable<int> CertificateFileId { get; set; }
    
        public virtual CertificateFile CertificateFile { get; set; }
    }
}
