//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryInfo
    {
        public int DeliveryInfoId { get; set; }
        public string ShippedVia { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> PackedBySignOffId { get; set; }
    
        public virtual SignOff SignOff { get; set; }
    }
}
