//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFile
    {
        public int EmployeeFileId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Filename { get; set; }
        public string FileURL { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
