//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingInspectionAccessory
    {
        public int IncomingInspectionAccessoryId { get; set; }
        public Nullable<int> PartId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool IsInstalled { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
