//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Parts = new HashSet<Part>();
            this.ChangeLogEntries = new HashSet<ChangeLogEntry>();
        }
    
        public int JobId { get; set; }
        public Nullable<int> CreatedByEmployeeId { get; set; }
        public Nullable<int> CustomerContactId { get; set; }
        public Nullable<int> JobStatusId { get; set; }
        public string CustomerJobNumber { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<System.DateTime> ShipByDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> BilledDate { get; set; }
        public Nullable<bool> OvertimeRequired { get; set; }
        public Nullable<bool> HoldForCustomerApproval { get; set; }
        public string JobNotes { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<bool> QuoteOnly { get; set; }
        public Nullable<bool> AllPartsRequireUT { get; set; }
        public Nullable<bool> AllPartsRequirePT { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeLogEntry> ChangeLogEntries { get; set; }
    }
}
