//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartFile()
        {
            this.PartTests = new HashSet<PartTest>();
            this.PartTests1 = new HashSet<PartTest>();
        }
    
        public int PartFileId { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<int> UpdatedByEmployeeId { get; set; }
        public string FileUrl { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsFinalPrint { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Part Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTest> PartTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTest> PartTests1 { get; set; }
    }
}
