//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartDiameterMeasurement
    {
        public int PartDiameterMeasurementId { get; set; }
        public Nullable<int> MeasurementListId { get; set; }
        public Nullable<System.DateTime> MeasuredDate { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public Nullable<decimal> C { get; set; }
        public string ODComment { get; set; }
    
        public virtual MeasurementList MeasurementList { get; set; }
    }
}
