//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartPhoto
    {
        public int PartPhotoId { get; set; }
        public Nullable<int> PartId { get; set; }
        public Nullable<int> PhotoTakenByEmployeeId { get; set; }
        public Nullable<int> PhotoTypeId { get; set; }
        public string PhotoUrl { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Part Part { get; set; }
        public virtual PhotoType PhotoType { get; set; }
    }
}
