//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.Processes = new HashSet<Process>();
            this.Sizes = new HashSet<Size>();
            this.IncomingInspectionAccessories = new HashSet<IncomingInspectionAccessory>();
            this.PartPhotoes = new HashSet<PartPhoto>();
            this.PartFiles = new HashSet<PartFile>();
            this.PartTests = new HashSet<PartTest>();
        }
    
        public int PartId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> PartTypeId { get; set; }
        public Nullable<int> PartStatusId { get; set; }
        public Nullable<int> PartContactId { get; set; }
        public string WorkScope { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<System.DateTime> ShipByDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string NonConformanceReportNotes { get; set; }
        public Nullable<bool> RequiresPT { get; set; }
        public Nullable<bool> RequiresUT { get; set; }
        public Nullable<int> PartProcessId { get; set; }
        public string ItemCode { get; set; }
        public string IdentifyingInfo { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process> Processes { get; set; }
        public virtual PartProcess PartProcess { get; set; }
        public virtual PartStatu PartStatu { get; set; }
        public virtual PartType PartType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Size> Sizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomingInspectionAccessory> IncomingInspectionAccessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartPhoto> PartPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartFile> PartFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartTest> PartTests { get; set; }
    }
}
