//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartTest
    {
        public int PartTestId { get; set; }
        public int PartId { get; set; }
        public Nullable<bool> UTComplete { get; set; }
        public Nullable<bool> PTComplete { get; set; }
        public Nullable<int> UTCertPartFileId { get; set; }
        public Nullable<int> PTCertPartFileId { get; set; }
        public string UTSignoffEmpName { get; set; }
        public string PTSignoffEmpName { get; set; }
        public Nullable<bool> UTPassed { get; set; }
        public Nullable<bool> PTPassed { get; set; }
        public string TestNotes { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual PartFile PartFile { get; set; }
        public virtual PartFile PartFile1 { get; set; }
    }
}
