//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public int SizesId { get; set; }
        public Nullable<int> PartId { get; set; }
        public string Shaft { get; set; }
        public string Clearance { get; set; }
        public string BoreSize { get; set; }
        public string BoreSizeHorizontal { get; set; }
        public string ShimSize { get; set; }
        public string Tolerance { get; set; }
        public string SealSize { get; set; }
        public string SpecialNotes { get; set; }
        public Nullable<int> CustomerSuppliedMeasurementsListId { get; set; }
    
        public virtual MeasurementList MeasurementList { get; set; }
        public virtual Part Part { get; set; }
    }
}
