//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Step()
        {
            this.StepActivities = new HashSet<StepActivity>();
        }
    
        public long StepId { get; set; }
        public int StepNumber { get; set; }
        public long ProcessId { get; set; }
        public string Title { get; set; }
        public string Version { get; set; }
        public string DataType { get; set; }
        public string StringValue { get; set; }
        public string Notes { get; set; }
        public string LastRequestedBy { get; set; }
        public Nullable<System.DateTime> Requested { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    
        public virtual Process Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepActivity> StepActivities { get; set; }
    }
}
