//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JDsDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetEntry
    {
        public int TimesheetEntryId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public System.DateTime Day { get; set; }
        public decimal NumHoursWorked { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> WorkedThroughMealtime { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
